name: lichi_test
description: lichi_test

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  dio: ^5.3.3
  sqflite: ^2.3.0
  flutter_riverpod: ^2.4.3
  freezed: ^2.4.5
  drift: ^2.12.1
  sqlite3_flutter_libs: ^0.5.17
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_bloc: ^8.1.3
  modal_bottom_sheet: ^2.1.2
  cached_network_image: ^3.3.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
dev_dependencies:
  drift_dev: ^2.12.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

